# config/edge_node.toml
[node]
id = "edge-001"
type = "raspberry-pi"
location = "factory-floor-1"

[inference]
model_path = "/models/current.onnx"
batch_size = 32
max_latency_ms = 50

[communication]
orchestrator_url = "https://orchestrator.neural-nexus.com"
mqtt_broker = "mqtt://broker.neural-nexus.com:1883"
